codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "55...80"
  status:
    project:
      default:
        target: 55%
        threshold: 2%
    patch:
      default:
        target: 50%

ignore:
  - "example/**"
  - "benchmark/**"
  - "integration/**"
  - "**/*_test.go"
  - "**/doc.go"
  - "vendor/**"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
