// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['main']['App']['Cancel'](arg1);
}

export function Chat(arg1) {
  return window['go']['main']['App']['Chat'](arg1);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function DeleteThread(arg1) {
  return window['go']['main']['App']['DeleteThread'](arg1);
}

export function GetThread(arg1) {
  return window['go']['main']['App']['GetThread'](arg1);
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function ListThreads() {
  return window['go']['main']['App']['ListThreads']();
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function SaveWindowState(arg1, arg2) {
  return window['go']['main']['App']['SaveWindowState'](arg1, arg2);
}

export function SendAction(arg1, arg2) {
  return window['go']['main']['App']['SendAction'](arg1, arg2);
}
