// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['main']['App']['Cancel'](arg1);
}

export function Chat(arg1) {
  return window['go']['main']['App']['Chat'](arg1);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function CreateProjectFolder(arg1) {
  return window['go']['main']['App']['CreateProjectFolder'](arg1);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function DeleteThread(arg1) {
  return window['go']['main']['App']['DeleteThread'](arg1);
}

export function GetAISettings() {
  return window['go']['main']['App']['GetAISettings']();
}

export function GetCurrentProject() {
  return window['go']['main']['App']['GetCurrentProject']();
}

export function GetKnowledgeStatus() {
  return window['go']['main']['App']['GetKnowledgeStatus']();
}

export function GetThread(arg1) {
  return window['go']['main']['App']['GetThread'](arg1);
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function ListDocTemplates() {
  return window['go']['main']['App']['ListDocTemplates']();
}

export function ListMcpServers() {
  return window['go']['main']['App']['ListMcpServers']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function ListThreads() {
  return window['go']['main']['App']['ListThreads']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function SaveWindowState(arg1, arg2) {
  return window['go']['main']['App']['SaveWindowState'](arg1, arg2);
}

export function SelectProjectFolder() {
  return window['go']['main']['App']['SelectProjectFolder']();
}

export function SendAction(arg1, arg2) {
  return window['go']['main']['App']['SendAction'](arg1, arg2);
}

export function SetAISettings(arg1) {
  return window['go']['main']['App']['SetAISettings'](arg1);
}

export function SwitchProject(arg1) {
  return window['go']['main']['App']['SwitchProject'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
