// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateTab(arg1) {
  return window['go']['main']['App']['ActivateTab'](arg1);
}

export function ActiveTabID() {
  return window['go']['main']['App']['ActiveTabID']();
}

export function BindThreadToSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['BindThreadToSession'](arg1, arg2, arg3);
}

export function Cancel(arg1) {
  return window['go']['main']['App']['Cancel'](arg1);
}

export function Chat(arg1) {
  return window['go']['main']['App']['Chat'](arg1);
}

export function ChatInTab(arg1, arg2) {
  return window['go']['main']['App']['ChatInTab'](arg1, arg2);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CloseTab(arg1) {
  return window['go']['main']['App']['CloseTab'](arg1);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function CreateProjectFolder(arg1) {
  return window['go']['main']['App']['CreateProjectFolder'](arg1);
}

export function CreateTab() {
  return window['go']['main']['App']['CreateTab']();
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function DeleteThread(arg1) {
  return window['go']['main']['App']['DeleteThread'](arg1);
}

export function ForgetMemory(arg1) {
  return window['go']['main']['App']['ForgetMemory'](arg1);
}

export function GetAISettings() {
  return window['go']['main']['App']['GetAISettings']();
}

export function GetCurrentProject() {
  return window['go']['main']['App']['GetCurrentProject']();
}

export function GetKnowledgeStatus() {
  return window['go']['main']['App']['GetKnowledgeStatus']();
}

export function GetThread(arg1) {
  return window['go']['main']['App']['GetThread'](arg1);
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function ListDocTemplates() {
  return window['go']['main']['App']['ListDocTemplates']();
}

export function ListMcpServers() {
  return window['go']['main']['App']['ListMcpServers']();
}

export function ListMemories(arg1) {
  return window['go']['main']['App']['ListMemories'](arg1);
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function ListTabs() {
  return window['go']['main']['App']['ListTabs']();
}

export function ListThreads() {
  return window['go']['main']['App']['ListThreads']();
}

export function ListTrashedThreads() {
  return window['go']['main']['App']['ListTrashedThreads']();
}

export function PurgeThread(arg1) {
  return window['go']['main']['App']['PurgeThread'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RecallMemories(arg1, arg2) {
  return window['go']['main']['App']['RecallMemories'](arg1, arg2);
}

export function RememberMemory(arg1) {
  return window['go']['main']['App']['RememberMemory'](arg1);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function RenameThread(arg1, arg2) {
  return window['go']['main']['App']['RenameThread'](arg1, arg2);
}

export function RestoreThread(arg1) {
  return window['go']['main']['App']['RestoreThread'](arg1);
}

export function SavePastedImage(arg1) {
  return window['go']['main']['App']['SavePastedImage'](arg1);
}

export function SaveWindowState(arg1, arg2) {
  return window['go']['main']['App']['SaveWindowState'](arg1, arg2);
}

export function SelectProjectFolder() {
  return window['go']['main']['App']['SelectProjectFolder']();
}

export function SendAction(arg1, arg2) {
  return window['go']['main']['App']['SendAction'](arg1, arg2);
}

export function SetAISettings(arg1) {
  return window['go']['main']['App']['SetAISettings'](arg1);
}

export function SwitchProject(arg1) {
  return window['go']['main']['App']['SwitchProject'](arg1);
}

export function TrashThread(arg1) {
  return window['go']['main']['App']['TrashThread'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
